//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS_System.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_Action
    {
        public Q_Action()
        {
            this.Q_ActionParameter = new HashSet<Q_ActionParameter>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Note { get; set; }
        public string Function { get; set; }
        public int Index { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Q_ActionParameter> Q_ActionParameter { get; set; }
    }
}
