//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS_System.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_Business
    {
        public Q_Business()
        {
            this.Q_DailyRequire = new HashSet<Q_DailyRequire>();
            this.Q_HisDailyRequire = new HashSet<Q_HisDailyRequire>();
        }
    
        public int Id { get; set; }
        public int BusinessTypeId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Note { get; set; }
        public int TotalTicket { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Q_BusinessType Q_BusinessType { get; set; }
        public virtual ICollection<Q_DailyRequire> Q_DailyRequire { get; set; }
        public virtual ICollection<Q_HisDailyRequire> Q_HisDailyRequire { get; set; }
    }
}
