//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS_System.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_Command
    {
        public Q_Command()
        {
            this.Q_CommandParameter = new HashSet<Q_CommandParameter>();
            this.Q_UserCommandReadSound = new HashSet<Q_UserCommandReadSound>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string CodeHEX { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Q_CommandParameter> Q_CommandParameter { get; set; }
        public virtual ICollection<Q_UserCommandReadSound> Q_UserCommandReadSound { get; set; }
    }
}
