//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS_System.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_CounterDayInfo
    {
        public int Id { get; set; }
        public int CounterId { get; set; }
        public int STT_QMS { get; set; }
        public string STT_3 { get; set; }
        public int STT { get; set; }
        public int STT_UT { get; set; }
        public Nullable<System.DateTime> PrintTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> ServeTime { get; set; }
        public int StatusSTT { get; set; }
        public int StatusSTT_UT { get; set; }
        public int EquipCode { get; set; }
    
        public virtual Q_Counter Q_Counter { get; set; }
    }
}
