//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS_System.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_DailyRequire_Detail
    {
        public Q_DailyRequire_Detail()
        {
            this.Q_UserEvaluate = new HashSet<Q_UserEvaluate>();
        }
    
        public int Id { get; set; }
        public int DailyRequireId { get; set; }
        public int MajorId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> EquipCode { get; set; }
        public Nullable<System.DateTime> ProcessTime { get; set; }
        public Nullable<System.DateTime> EndProcessTime { get; set; }
        public int StatusId { get; set; }
    
        public virtual Q_DailyRequire Q_DailyRequire { get; set; }
        public virtual Q_Major Q_Major { get; set; }
        public virtual Q_Status Q_Status { get; set; }
        public virtual Q_User Q_User { get; set; }
        public virtual ICollection<Q_UserEvaluate> Q_UserEvaluate { get; set; }
    }
}
