//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS_System.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_EquipmentType
    {
        public Q_EquipmentType()
        {
            this.Q_Equipment = new HashSet<Q_Equipment>();
            this.Q_EquipTypeProcess = new HashSet<Q_EquipTypeProcess>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Q_Equipment> Q_Equipment { get; set; }
        public virtual ICollection<Q_EquipTypeProcess> Q_EquipTypeProcess { get; set; }
    }
}
