//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS_System.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_EvaluateDetail
    {
        public int Id { get; set; }
        public int EvaluateId { get; set; }
        public int Index { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public bool IsDefault { get; set; }
        public string Icon { get; set; }
        public bool IsSendSMS { get; set; }
        public string SmsContent { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Q_Evaluate Q_Evaluate { get; set; }
    }
}
