//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS_System.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_HisDailyRequire_WorkDetail
    {
        public int Id { get; set; }
        public int HisDailyRequireId { get; set; }
        public int WorkDetailId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Q_HisDailyRequire Q_HisDailyRequire { get; set; }
        public virtual Q_WorkDetail Q_WorkDetail { get; set; }
    }
}
