//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS_System.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_Language
    {
        public Q_Language()
        {
            this.Q_CounterSound = new HashSet<Q_CounterSound>();
            this.Q_ReadTemplate = new HashSet<Q_ReadTemplate>();
            this.Q_Sound = new HashSet<Q_Sound>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Q_CounterSound> Q_CounterSound { get; set; }
        public virtual ICollection<Q_ReadTemplate> Q_ReadTemplate { get; set; }
        public virtual ICollection<Q_Sound> Q_Sound { get; set; }
    }
}
