//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS_System.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_Schedule_Detail
    {
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public int ScheduleId { get; set; }
        public int CustomerId { get; set; }
        public int KhungGioId { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Q_Customer Q_Customer { get; set; }
        public virtual Q_KhungGio Q_KhungGio { get; set; }
        public virtual Q_Schedule Q_Schedule { get; set; }
        public virtual Q_Service Q_Service { get; set; }
    }
}
