//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS_System.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_Shift
    {
        public Q_Shift()
        {
            this.Q_ServiceShift = new HashSet<Q_ServiceShift>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Q_ServiceShift> Q_ServiceShift { get; set; }
    }
}
