//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS_System.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_Status
    {
        public Q_Status()
        {
            this.Q_DailyRequire_Detail = new HashSet<Q_DailyRequire_Detail>();
            this.Q_Equipment = new HashSet<Q_Equipment>();
            this.Q_HisDailyRequire_De = new HashSet<Q_HisDailyRequire_De>();
            this.Q_Login = new HashSet<Q_Login>();
            this.Q_LoginHistory = new HashSet<Q_LoginHistory>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int StatusTypeId { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<Q_DailyRequire_Detail> Q_DailyRequire_Detail { get; set; }
        public virtual ICollection<Q_Equipment> Q_Equipment { get; set; }
        public virtual ICollection<Q_HisDailyRequire_De> Q_HisDailyRequire_De { get; set; }
        public virtual ICollection<Q_Login> Q_Login { get; set; }
        public virtual ICollection<Q_LoginHistory> Q_LoginHistory { get; set; }
        public virtual Q_StatusType Q_StatusType { get; set; }
    }
}
