//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS_System.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_TVReadSound
    {
        public int Id { get; set; }
        public string Sounds { get; set; }
        public string UsersReaded { get; set; }
        public Nullable<int> CounterId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Q_Counter Q_Counter { get; set; }
    }
}
