//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS_System.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_UserCmdRegister
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int CmdParamId { get; set; }
        public int ActionParamId { get; set; }
        public string Param { get; set; }
        public int Index { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Q_ActionParameter Q_ActionParameter { get; set; }
        public virtual Q_CommandParameter Q_CommandParameter { get; set; }
        public virtual Q_User Q_User { get; set; }
    }
}
