//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS_System.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_WorkDetail
    {
        public Q_WorkDetail()
        {
            this.Q_DailyRequire_WorkDetail = new HashSet<Q_DailyRequire_WorkDetail>();
            this.Q_HisDailyRequire_WorkDetail = new HashSet<Q_HisDailyRequire_WorkDetail>();
        }
    
        public int Id { get; set; }
        public int WorkId { get; set; }
        public System.DateTime TimeProcess { get; set; }
        public bool IsDeleted { get; set; }
        public int WorkTypeId { get; set; }
    
        public virtual Q_Works Q_Works { get; set; }
        public virtual Q_WorkType Q_WorkType { get; set; }
        public virtual ICollection<Q_DailyRequire_WorkDetail> Q_DailyRequire_WorkDetail { get; set; }
        public virtual ICollection<Q_HisDailyRequire_WorkDetail> Q_HisDailyRequire_WorkDetail { get; set; }
    }
}
